### ISSUE TITLE
Open report output file after test finished

### ISSUE THREAD

**Issue by giordano91** [matthias-schuetz/karma-htmlfile-reporter#23]
Hi matthias-schuetz, 
first of all thank you for your karma-htmlfile-reporter project!
I would like use it in a project, but i'd like to know if there is a way to open directly after tests the output file.

Thank you so much.

Best regards

**Comment by matthias-schuetz** [comment]
I can't integrate such a feature in karma-htmlfile-reporter since it's only a reporter and so it has boundaries.

But you can accomplish your task by creating a certain launch file for Karma and then open the unit test file afterwards. Opening files or URLs in the browser is not trivial since it differs for each operating system. So you need a small module to do that. It's called `opn` and you need to install it locally where you have your `karma.conf.js`.

`npm install --save opn`

So you would install `opn` and create a `karma.launch.js` besides your `karma.conf.js` afterwards.

The `karma.launch.js` would look like this

```javascript
var opn = require('opn');
var path = require('path');
var KarmaServer = require('karma').Server;

var karmaServer = new KarmaServer({
  configFile: path.resolve('./karma.conf.js'),
}, function(exitCode) {
  process.exit(exitCode);
});

karmaServer.on('run_complete', function(browsers, runResult) {
  opn(path.resolve('./tests/units.html'), { app: 'chrome' });
});

karmaServer.start();
```

From now on, you would run your Karma tests via the command
`node karma.launch.js`

I hope this helps!

**Comment by giordano91** [comment]
Thank you so much for your reply and your suggestion.
I will try in this way.

Thank you
